apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  push:
    branches:
      - 'master'

stages:
  - build
build:
  stage: build
  image: gradle:8.3
  script:
    - echo "Building Application"
    - chmod -R 777 gradlew 
    - ./gradlew build
