apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "master"
jobs:
  build:
    steps:
      - name: Build with Gradle
        uses: docker://gradle:latest
        shell: sh
        run: |
          ./gradlew build
